[tool.briefcase]
project_name = "YourApp"
version = "0.1.0"
bundle = "com.yourdomain"
license = "MIT"
author = "Your Name"
author_email = "your.email@example.com"

[tool.briefcase.app.yourapp]
formal_name = "Your App"
description = "Your app description"
sources = ["src/yourapp"]
requires = []
