name: Build
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - run: pip install ruff black
      - name: Find project directory
        shell: bash
        run: |
          PROJECT_DIR=$(find . -type d -name src -exec dirname {} \; | head -n 1)
          echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV
      - run: black --check ${{ env.PROJECT_DIR }}/src
      - run: ruff check ${{ env.PROJECT_DIR }}

  build:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - run: python -m pip install briefcase
      - name: Install dependencies
        run: sudo apt install libgirepository1.0-dev
      - name: Find project directory
        shell: bash
        run: |
          PROJECT_DIR=$(find . -type d -name src -exec dirname {} \; | head -n 1)
          echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV
      #  - run: cd ${{ env.PROJECT_DIR }} && briefcase create
      - run: cd ${{ env.PROJECT_DIR }} && briefcase build
      - run: cd ${{ env.PROJECT_DIR }} && briefcase package --adhoc-sign
      - uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.os }}
          path: |
            ${{ env.PROJECT_DIR }}/dist/*.deb
            ${{ env.PROJECT_DIR }}/dist/*.msi
            ${{ env.PROJECT_DIR }}/dist/*.dmg
