name: Windows Build

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed
    branches: [main]

jobs:
  build-windows:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Build with PyInstaller
        run: |
          pyinstaller --clean --onefile `
            --name "pdf-converter" `
            --windowed `
            src/pdf_converter/app.py

      - name: Create ZIP archive
        run: |
          Compress-Archive -Path "dist/pdf-converter.exe" -DestinationPath "dist/pdf-converter-windows.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf-converter-windows
          path: dist/pdf-converter-windows.zip
