name: PyInstaller Build and Release

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.platform }}-${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x86_64
          - os: ubuntu-latest
            platform: linux
            arch: aarch64
          - os: ubuntu-latest
            platform: windows
            arch: x86_64
          - os: ubuntu-latest
            platform: macos
            arch: x86_64
          - os: ubuntu-latest
            platform: macos
            arch: arm64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Set up QEMU
        if: matrix.arch == 'aarch64' || matrix.arch == 'arm64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Install cross-compilation tools
        if: matrix.platform != 'windows'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Install Windows cross-compilation tools
        if: matrix.platform == 'windows'
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64

      - name: Build with PyInstaller
        env:
          PLATFORM: ${{ matrix.platform }}
          ARCH: ${{ matrix.arch }}
        run: |
          pyinstaller --clean --onefile \
            --name "docling-converter-$PLATFORM-$ARCH" \
            --add-data "src/docling_converter/resources:docling_converter/resources" \
            src/docling_converter/app.py

      - name: Create ZIP archive
        run: |
          cd dist
          if [ "${{ matrix.platform }}" = "windows" ]; then
            zip "docling-converter-${{ matrix.platform }}-${{ matrix.arch }}.zip" "docling-converter-${{ matrix.platform }}-${{ matrix.arch }}.exe"
          else
            zip "docling-converter-${{ matrix.platform }}-${{ matrix.arch }}.zip" "docling-converter-${{ matrix.platform }}-${{ matrix.arch }}"
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: docling-converter-${{ matrix.platform }}-${{ matrix.arch }}
          path: dist/docling-converter-${{ matrix.platform }}-${{ matrix.arch }}.zip

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            */docling-converter-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
