name: Code Quality

on:
  push:
    branches:
      - "**" # Run on all branches

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run Ruff (lint and format)
        run: |
          ruff check .
          ruff format --check .

      - name: Run MyPy
        run: mypy src

      # - name: Check dependencies for known vulnerabilities
      #   run: |
      #     safety check
